### ISSUE TITLE
Anyway to skip already liked posts?

### ISSUE THREAD

**Issue by SharkLava** [taichikuji/AniLiker#11]
Currently posts that have already been liked get unliked when the bot runs through that page. Is there anyway to stop this? I am not familiar with the API so forgive me if I'm missing something obvious.

**Comment by taichikuji** [comment]
Hello! First of all, thanks for creating this issue!

Yes, there's a way, the API allows you to check each post's status which means you'd be able to check if you have liked a post or not. It's currently not implemented anywhere since I planned on keeping it simple and fast.

I did not do my research back then with this, since I didn't see the need for it, but it seems that, if you get the query I generate to get every ID possible, you can definitely do it.

```PYTHON
query ($user_id: Int, $page: Int, $perPage: Int) {
              Page (page: $page, perPage: $perPage) {
                pageInfo {
                    hasNextPage
                  }
                activities (userId: $user_id, sort: ID_DESC) {
                    ... on ListActivity {
                      id
                      isLiked
                  }
                  ... on TextActivity {
                      id
                      isLiked
                      }
                  ... on MessageActivity {
                    id
                    isLiked
                  }
                }
              }
            }
````

What I'm not sure about, is if I'd be able to implement it to the mutation ToggleLikeV2:

```PYTHON
          mutation ($id: Int) {
            ToggleLikeV2(id: $id, type: ACTIVITY) {
              __typename
            }
          }
```

If you go to [Anilist's GraphQL sandbox](https://anilist.co/graphiql) you can test as much as you want, and then comment your results!

**Comment by taichikuji** [comment]
Okay I think I found a way! I'll make a PR, link it to this issue and then add the feature!

Thanks again for generating this issue.
