### ISSUE TITLE
Create guide to explain how to get the script working

### ISSUE THREAD

**Issue by ligr98** [taichikuji/AniLiker#44]
I'm a complete newbie when it comes to this stuff I've managed to get to the point of entering a username however I get these errors.

<Response [400]>
Traceback (most recent call last):
  line 138, in <module>
    main()
  line 76, in main
    user_id = run_query(query, variables)["User"]["id"]
   line 44, in run_query
    raise Exception("AniList query failed!")
Exception: AniList query failed!

**Comment by taichikuji** [comment]
First of all, thank you very much for creating this issue! I will test it ASAP.
Can you please tell me the username that is giving you an issue?
Is it just one username or multiple?
Can you tell me your Python version and also Operative System? Thanks!

**Comment by taichikuji** [comment]
I just tested it on Windows, through a current installation of Python 3.8 and it worked fine for me. I will explain the steps that you need to take to get the script working.

First of all you have two options to run the script. One is a WebUI option, basically, visit [https://replit.com/@OkWeeb/AniLiker](https://replit.com/@OkWeeb/AniLiker) and follow the steps. It should run just fine if you do it correctly.

The second option is doing it locally, even if you do it on Linux or Windows, you require Python 3.8 to get it working, since it's specificated on the Pipfile. Through Pipfile you can get all the packages with the version they need to be up-to-date and working flawlessly!

If you're getting issues configuring your API key from AL, you can follow my Wiki Guide here: [https://github.com/taichikuji/AniLiker/wiki/Create-AL-API-Client](https://github.com/taichikuji/AniLiker/wiki/Create-AL-API-Client)

If not, just input the values inside the .env file on your project folder, and it should prompt you with some text to follow. Will link to the text for you as well here: [https://github.com/taichikuji/AniLiker/blob/27a74fcdf2d3046494d267e6936934b467be16eb/utils/oauth.py#L12](https://github.com/taichikuji/AniLiker/blob/27a74fcdf2d3046494d267e6936934b467be16eb/utils/oauth.py#L12)

If you require, I could create a simple Wiki guide to show how the script needs to be setup to the point of getting it working.

**Comment by ligr98** [comment]
Hi there I thought I'd try the web one to see if I had any luck and I am getting the exact same error so I tried doing the token thing again but through the web version and its throwing me errors so it makes me wonder if the source of it is I haven't set the Token up properly, I've tried multiple ways and I keep getting an error occurred when pasting the full redirect url so now I am even more confused.

**Comment by taichikuji** [comment]
Don't worry, I will make a guide once I find time. I will link it here once I finish it :)

**Comment by itsuki1simp** [comment]
Pretty sure this happens when you get the Cloudfare protection thing. I don't know how to get rid of it except using a vpn to access the site (didn't work on the script) 
Hopefully the creator will fix this issue soon!

**Comment by itsuki1simp** [comment]
Update: I used NordVPN to change my ip, and now it works.
The issue is Cloudfare protection

**Comment by taichikuji** [comment]
I'm testing a new version of AniLiker on [Replit](https://replit.com/@OkWeeb/AniLiker#main.py) and it seems to be working now. I will however continue with the guide ASAP.

**Comment by taichikuji** [comment]
I have created the Wiki guide. Please check it out and tell me if through this guide you got it working! Thank you for your time :)

[AniLiker's Wiki: How to AniLiker](https://github.com/taichikuji/AniLiker/wiki/How-to-AniLiker)

**Comment by ligr98** [comment]
Hi there thanks so much for your help I tried it again I had done everything the same and now it just works now lmao, thanks again!

**Comment by taichikuji** [comment]
I'm glad to hear that it works again for you!
